Replace PBKDF2 with Argon2id
zorggish/FractalCryptGUI pull request #10
Opened 2024-07-17 11:50 UTC by umutcamliyurt

2024-07-18 17:41 UTC, zorggomat requested changes

2024-07-18 17:41 UTC, zorggomat commented on core/aes.cpp
> +        std::generate(key.begin(), key.end(), [&random]() { return random->generate(); });
Why `std::generate` is better than `random->generate`?

2024-07-18 18:25 UTC, umutcamliyurt commented on core/aes.cpp
> +        std::generate(key.begin(), key.end(), [&random]() { return random->generate(); });
std::generate with a lambda function is better because it correctly fills the container with random values, ensuring simplicity and correctness.

2024-07-31 18:53 UTC, zorggomat requested changes

2024-07-31 18:53 UTC, zorggomat commented on core/aes.h
> +    bool processFile(QIODevice *file, qint64 pos, qint64 end, const QByteArray &key, bool encrypt);
Variable "encrypt" should not have boolean type, we have a "Mode" type for this

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +#include <argon2.h>
We should write `#include "argon2.h"` because it is a local project file

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +#define IV_SIZE 16
The idea of using named values instead of magic numbers is good, but defines is deprecated, we should use compile-time constants

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +void AES::setRange(qint64 pos, qint64 end) { this->pos = pos; this->end = end; }
Do not write methods in one line please, it makes debugging more difficult

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +    key.resize(KEY_SIZE);
If the key always has this length, we should initialize it with this value rather than calling the `resize` method each time we set the password

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +    if (end - pos >= 16 * 1024 * 1024) emit started();
Put `emit` on a new line please, I used to write in one line myself, but now I realize it makes it worse

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> -    const qint64 bufferSize = 4096;
"BufferSize" is only used inside the function, so we can leave its declaration here

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> -    if(!ctx) return false;
Uninitialized ctx will cause the program to crash, so we should keep checking it

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +        if (file->read(buffer.data(), additional) != additional) return false;
Please move the return to the next line, to facilitate debugging

2024-07-31 18:53 UTC, zorggomat commented on core/aes.cpp
> +bool AES::isSuccess() const { return success; }
We shouldn't write it in one line, either

2024-08-01 05:01 UTC, umutcamliyurt commented
All issues are fixed and code works correctly

2024-08-05 10:19 UTC, zorggomat approved these changes

2024-08-05 10:20 UTC, merged