Replace PBKDF2 with Argon2id
zorggish/FractalCryptGUI pull request #9
Opened 2024-07-09 13:29 UTC by umutcamliyurt

Build and test it before merging

2024-07-09 15:52 UTC, umutcamliyurt commented
If it doesn't work on your system i will use hardcoded salt. Is this ok for you?

2024-07-09 17:59 UTC, zorggomat commented
@umutcamliyurt hello! Please give me a little time so I can check the changes and build and test the project. Thank you for your participation. My email is xenomat@yandex.ru

2024-07-11 19:29 UTC, zorggomat commented
Hello @umutcamliyurt 
I wrote comments on your pull-request.
Also it would be great if you give me your email too.

2024-07-11 19:32 UTC, umutcamliyurt commented
Thank you for your quick review :) My e-mail is: nemesisuks@protonmail.com

2024-07-12 06:06 UTC, umutcamliyurt commented
My e-mail: nemesisuks@outlook.com

2024-07-14 05:54 UTC, umutcamliyurt commented
Do my e-mails reach you? I think protonmail and outlook maybe blocked in russia

2024-07-15 08:15 UTC, zorggomat requested changes

2024-07-15 08:15 UTC, zorggomat commented on FractalCryptGUI.pro
Do we really need a second pro file?

2024-07-15 08:15 UTC, zorggomat commented on LICENSE
> +Copyright (c) 2024 Nemesis
I think you should add rather than replace

2024-07-15 08:15 UTC, zorggomat commented on core/aes.cpp
> +AES::AES() : device(nullptr), pos(0), end(0), mode(Encrypt), success(false)
It is more proper to initialize fields in the order they are defined
`AES::AES() : mode(Encrypt), device(nullptr), pos(0), end(0), success(false)`

2024-07-15 08:15 UTC, zorggomat commented on core/aes.cpp
> +        for (int i = 0; i < key.size(); ++i)
For what reason did you choose to use the loop instead of calling a function with iterators?

2024-07-15 08:15 UTC, zorggomat commented on core/aes.cpp
> +    unsigned char outBuffer[bufferSize + EVP_CIPHER_block_size(EVP_aes_256_xts())];
I failed to build this
```
error C2131: expression did not evaluate to a constant
note: failure was caused by call of undefined function or one not declared 'constexpr'
note: see usage of 'EVP_aes_256_xts'
```

2024-07-15 11:26 UTC, umutcamliyurt commented on FractalCryptGUI.pro
Deleted FractalCryptGUI.pro

2024-07-15 11:27 UTC, umutcamliyurt commented on LICENSE
> +Copyright (c) 2024 Nemesis
Added it

2024-07-17 08:50 UTC, zorggomat requested changes

2024-07-17 08:50 UTC, zorggomat commented on FractalCryptGUI.pro
File still exists

2024-07-17 08:50 UTC, zorggomat commented on core/aes.cpp
> +#include <argon2.h>
It is better to use `#include "argon2.h` because the header is located in the local directory

2024-07-17 11:28 UTC, umutcamliyurt commented on core/aes.cpp
> +#include <argon2.h>
fixed

2024-07-17 11:28 UTC, umutcamliyurt commented on FractalCryptGUI.pro
Deleted the file

2024-07-17 11:40 UTC, closed without merging